import { Metadata } from "next"
import "./globals.css";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: 'Next.js - 1',
    template: "%s | My code"
  },
  description: 'Generated by Next.js -1 ',
}

interface RootLayoutProps {
  children: React.ReactNode;
  navbar: React.ReactNode;
  sidebar: React.ReactNode;
}

export default function RootLayout({ children, navbar, sidebar }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <div>{navbar}</div>
        <div className="container mx-auto">

          {/* <div>{sidebar}</div> */}
          <header style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}>
            <p>Header</p>
          </header>
          {children}
          <footer style={{
            backgroundColor: "ghostWhite",
            padding: "1rem"
          }}>
            <p>Footer</p>
          </footer>
        </div>
      </body>
    </html>
  )
}